name: newsapi_client
description: A client for the newsapi.org API (v2) written in dart. You can get access to the API by signing up at https://newsapi.org.
version: 0.2.2
author: Sander Dalby Larsen <srdlarsen@gmail.com>
homepage: https://github.com/salby/newsapi_client
environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  http: ^0.12.0

dev_dependencies:
  test: ^1.5.1
