name: newsapi_client
description: A dartlang client for the newsapi.org API.
version: 0.1.0
author: Sander Dalby Larsen <srdlarsen@gmail.com>
homepage: https://github.com/salby/newsapi_client

dependencies:
  http: ^0.12.0
